export const getUsers = async (req, res, next) => {
    try {
    } catch (error) {

    }
}